# Generated by Django 2.2.2 on 2019-06-18 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='c100_mp_3_8x10G',
            fields=[
                ('test_name', models.CharField(max_length=100)),
                ('build', models.CharField(max_length=30)),
                ('test_type', models.CharField(max_length=20)),
                ('results', models.IntegerField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
